In [1]:
import numpy as np

In [2]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
# some more arange examples:
x = np.arange(10.4)
print(x)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [4]:
x = np.arange(0.5, 10.4, 0.8)
print(x)

[  0.5   1.3   2.1   2.9   3.7   4.5   5.3   6.1   6.9   7.7   8.5   9.3
  10.1]


In [5]:
x = np.arange(0.5, 10.4, 0.8, int)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
