In [1]:
import numpy as np

In [2]:
E = np.ones((2,3))
print(E)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [3]:
F = np.ones((3,4),dtype=int)
print(F)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
Z = np.zeros((2,4))
print(Z)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [5]:
x = np.array([2,5,18,14,4])
E = np.ones_like(x)
print(E)
Z = np.zeros_like(x)
print(Z)

[1 1 1 1 1]
[0 0 0 0 0]
