In [1]:
import numpy as np

In [2]:
x = np.array([[42,22,12],[44,53,66]], order='F')
y = x.copy()

In [3]:
x[0,0] = 1001
print(x)
print(y)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]


In [4]:
print(x.flags['C_CONTIGUOUS'])
print(y.flags['C_CONTIGUOUS'])

False
True


In [5]:
x = np.array([[42,22,12],[44,53,66]], order='F')
y = x.copy()

In [6]:
x[0,0] = 1001
print(x)
print(y)
print(x.flags['C_CONTIGUOUS'])
print(y.flags['C_CONTIGUOUS'])

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]
False
True
