In [52]:
import numpy as np

In [53]:
i16 = np.dtype(np.int16)
print(i16)

int16


In [54]:
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]
A = np.array(lst, dtype=i16)
print(A)

[[ 3  8  9]
 [ 1 -7  0]
 [ 4 12  4]]


In [55]:
dt = np.dtype([('density', np.int32)])
x = np.array([(393,), (337,), (256,)],
             dtype=dt)
print(x)
print("\nThe internal representation:")
print(repr(x))

[(393,) (337,) (256,)]

The internal representation:
array([(393,), (337,), (256,)], 
      dtype=[('density', '<i4')])


In [56]:
print(x['density'])

[393 337 256]


In [57]:
dt = np.dtype([('density', 'i4')])
x = np.array([(393,), (337,), (256,)],
             dtype=dt)
print(x)

[(393,) (337,) (256,)]


In [58]:
dt = np.dtype('<d') 
print(dt.name, dt.byteorder, dt.itemsize)
dt = np.dtype('>d')  
print(dt.name, dt.byteorder, dt.itemsize)
dt = np.dtype('d') 
print(dt.name, dt.byteorder, dt.itemsize)

('float64', '=', 8)
('float64', '>', 8)
('float64', '=', 8)


In [59]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
x = np.array([('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813),
('Ireland', 65, 70280, 4581269),
('Sweden', 20, 449964, 9515744),
('Finland', 16, 338424, 5410233),
('Norway', 13, 385252, 5033675)],
             dtype=dt)

In [60]:
print (x)
print(x[:4])

[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)
 ('Liechtenstein', 205,    160,    32842) ('Italy', 192, 301230, 59715625)
 ('Switzerland', 177,  41290,  7301994)
 ('Luxembourg', 173,   2586,   512000) ('France', 111, 547030, 63601002)
 ('Austria',  97,  83858,  8169929) ('Greece',  81, 131940, 11606813)
 ('Ireland',  65,  70280,  4581269) ('Sweden',  20, 449964,  9515744)
 ('Finland',  16, 338424,  5410233) ('Norway',  13, 385252,  5033675)]
[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)]


In [61]:
print(x['density'])
print(x['country'])
print(x['area'][2:5])

[393 337 256 233 205 192 177 173 111  97  81  65  20  16  13]
['Netherlands' 'Belgium' 'United Kingdom' 'Germany' 'Liechtenstein' 'Italy'
 'Switzerland' 'Luxembourg' 'France' 'Austria' 'Greece' 'Ireland' 'Sweden'
 'Finland' 'Norway']
[243610 357021    160]


In [62]:
time_type = np.dtype( [('h', int), ('min', int), ('sec', int)])
times = np.array([(11, 38, 5), 
                  (14, 56, 0),
                  (3, 9, 1)], dtype=time_type)
print(times)
print(times[0])
# reset the first time record:
times[0] = (11, 42, 17)
print(times[0])

[(11, 38, 5) (14, 56, 0) ( 3,  9, 1)]
(11, 38, 5)
(11, 42, 17)


In [63]:
time_type = np.dtype( np.dtype([('time', [('h', int), ('min', int), ('sec', int)]),
                                ('temperature', float)] ))
times = np.array( [((11, 42, 17), 20.8), ((13, 19, 3), 23.2) ], dtype=time_type)

In [64]:
print(times)
print(times['time'])
print(times['time']['h'])
print(times['temperature'])

[((11, 42, 17),  20.8) ((13, 19,  3),  23.2)]
[(11, 42, 17) (13, 19,  3)]
[11 13]
[ 20.8  23.2]


In [3]:
import pickle

lines = open("cities_and_times.txt").readlines()
lines.sort()

cities = []
for line  in lines:
    *city, day, time = line.split()
    hours, minutes = time.split(":")
    cities.append((" ".join(city), day, (int(hours), int(minutes)) ))

fh = open("citiesandtimes.pkl", "bw")
pickle.dump(cities, fh)

SyntaxError: invalid syntax (<ipython-input-3-07200f965cf2>, line 8)

In [32]:
fh = open('citiesandtimes.pkl','rb')
cities_and_times=pickle.load(fh)
print(cities_and_times[:30])

['Chicago\tSun 01:52\r\nColumbus Sun 02:52\r\nRiyadh\tSun 10:52\r\nCopenhagen\tSun 08:52\r\nKuwait City\tSun 10:52\r\nRome\tSun 08:52\r\nDallas\tSun 01:52\r\nSalt Lake City\tSun 01:52\r\nSan Francisco Sun 00:52\r\nAmsterdam Sun 08:52\r\nDenver Sun 01:52\r\nSan Salvador Sun 01:52\r\nDetroit\tSun 02:52\r\nLas Vegas Sun 00:52\r\nSantiago\tSun 04:52\r\nAnchorage Sat 23:52\r\nAnkara Sun 10:52\r\nLisbon\tSun 07:52\r\nS\xc3\x83\xc2\xa3o Paulo\tSun 05:52\r\nDubai\tSun 11:52\r\nLondon\tSun 07:52\r\nSeattle\tSun 00:52\r\nDublin\tSun 07:52\r\nLos Angeles Sun 00:52\r\nAthens\tSun 09:52\r\nEdmonton Sun 01:52\r\nMadrid\tSun 08:52\r\nShanghai Sun 15:52\r\nAtlanta\tSun 02:52\r\nFrankfurt\tSun 08:52\r\nSingapore Sun 15:52\r\nAuckland Sun 20:52\r\nHalifax\tSun 03:52\r\nMelbourne Sun 18:52\r\nStockholm\tSun 08:52\r\nBarcelona\tSun 08:52\r\nMiami\tSun 02:52\r\nMinneapolis\tSun 01:52\r\nSydney Sun 18:52\r\nBeirut\tSun 09:52\r\nHelsinki\tSun 09:52\r\nMontreal\tSun 02:52\r\nBerlin\tSun 08:52\r\nHouston\tSun 

In [34]:
time_type = np.dtype([('city', 'U30'), ('day', 'U3'), ('time', [('h', int), ('min', int)])])
times = np.array( cities_and_times , dtype=time_type)
print(times['time'])
print(times['city'])
x = times[27]
x[0]

[(8389187215163208245, 7584941817387371552)]
[ u'\U63696843\U096f6761\U206e7553\U353a3130\U430a0d32\U6d756c6f\U20737562\U206e7553\U353a3230\U520a0d32\U64617969\U75530968\U3031206e\U0d32353a\U706f430a\U61686e65\U096e6567\U206e7553\U353a3830\U4b0a0d32\U69617775\U69432074\U53097974\U31206e75\U32353a30\U6f520a0d\U5309656d\U30206e75\U32353a38\U61440a0d']


IndexError: index 27 is out of bounds for axis 0 with size 1