In [2]:
import numpy as np

In [3]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

In [4]:
# print the first element of F, i.e. the element with the index 0
print(F[0])
# print the last element of F
print(F[-1])

1
21


In [5]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B[0][1][0])

121


In [6]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(A[1][0])

1.1


In [7]:
tmp = A[1]
print(tmp)
print(tmp[0])

[ 1.1 -7.8 -0.7]
1.1


In [8]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])
print(S[:])

[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
A = np.array([
[11,12,13,14,15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51,52,53,54,55]])

In [10]:
print(A[:3,2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [12]:
print(A[3:,:])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [14]:
print(A[:,3:])

[[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]]


In [15]:
X = np.arange(28).reshape(4,7)
print(X)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [17]:
print(X[::3, ::2])

[[ 0  2  4  6]
 [21 23 25 27]]


In [19]:
print(X[::, ::2])

[[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]
 [21 23 25 27]]


In [20]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
S[0] = 22
S[1] = 23
print(A)

[ 0  1 22 23  4  5  6  7  8  9]


In [21]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
lst2 = lst[2:6]
lst2[0] = 22
lst2[1] = 23
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
np.may_share_memory(A, S)

True

In [23]:
A = np.arange(12)
B = A.reshape(3, 4)
A[0] = 42
print(B)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
print(A.data)
print(B.data)
print(A.data == B.data)

*	

*	

True


In [25]:
print(A == B)

False


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


In [26]:
print(A)
print(B)

[42  1  2  3  4  5  6  7  8  9 10 11]
[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
np.may_share_memory(A, B)

True