In [1]:
import numpy as np

In [2]:
#Zero-dimensional Arrays in Numpy
#var declaration
x = np.array(42)
#printing
print("x: ", x)
print("The type of x: ", type(x))
print("The dimension of x:", np.ndim(x))

In [3]:
#One-dimensional Arrays
#var declaration
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
#printing
print("F: ", F)
print("V: ", V)
print("Type of F: ", F.dtype)
print("Type of V: ", V.dtype)
print("Dimension of F: ", np.ndim(F))
print("Dimension of V: ", np.ndim(V))

('x: ', array(42))
('The type of x: ', <type 'numpy.ndarray'>)
('The dimension of x:', 0)


In [4]:
#Two Dimentional Arrays
#var declaration
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
#printing
print(A)
print(A.ndim)

In [10]:
#Multidimensional Arrays
#var declaration
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
#printing
print(B)
print(B.ndim)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
3
