In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [7]:
odd_indices=a[1::2]
print odd_indices

[2 4]


In [8]:
reverse=a[::-1]
print reverse

[5 4 3 2 1]


In [10]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


In [14]:
b=np.array([[1,2,3,4,5],
          [6,7,8,9,10]])
print b

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
reverse_m=b[::-1]
print reverse_m

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [16]:
reverse_m_rw=b[::,::-1]
print reverse_m_rw

[[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [18]:
reverse_m_rw_cl= b[::,::-1]
print reverse_m_rw_cl

[[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [21]:
cut=b[1:-1,1:-1]
print cut

[]
